= Service Discovery in Container Orchestration Frameworks on AWS

This repo has a simple example that shows service discovery for different container orchestration frameworks.

== Build services

This is an optional step as images are already available in Docker Hub.

```
docker-compose build
```

Three services:

                  |-------> greeter-service
webapp-service ---
                  |-------> name-service

. `webapp-service`: A simple Node.js application that queries `greeter` and `name` service to generate a greeting.
. `greeter-service`: A simple Node.js application that returns a greeting based upon abbreviation identified using `greet` name/value keypair in the URL
. `name-service`: A simple Node.js application that returns a name based upon id identified using `id` name/value keypair in the URL

== Run services

=== Using Docker

```
docker swarm init
docker stack up --compose-file=docker-compose.yml webapp
```

== Access service using web application

Access the following URLs:

```
http://localhost:8080
http://localhost:8080?greet=ho
http://localhost:8080?id=1
http://localhost:8080?greet=ho&id=1
```

== Delete services

=== Using Docker

```
docker stack rm webapp
docker swarm leave -f
```

